"""empty message

Revision ID: 04940efb90e6
Revises: 
Create Date: 2024-05-16 10:17:38.288810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04940efb90e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors_table.id'], name=op.f('fk_appointments_table_doctor_id_doctors_table')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients_table.id'], name=op.f('fk_appointments_table_patient_id_patients_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments_table')
    op.drop_table('patients_table')
    op.drop_table('doctors_table')
    # ### end Alembic commands ###
